# Copyright (c) 2021-2025, InterDigital Communications, Inc
# All rights reserved.

# Redistribution and use in source and binary forms, with or without
# modification, are permitted (subject to the limitations in the disclaimer
# below) provided that the following conditions are met:

# * Redistributions of source code must retain the above copyright notice,
#   this list of conditions and the following disclaimer.
# * Redistributions in binary form must reproduce the above copyright notice,
#   this list of conditions and the following disclaimer in the documentation
#   and/or other materials provided with the distribution.
# * Neither the name of InterDigital Communications, Inc nor the names of its
#   contributors may be used to endorse or promote products derived from this
#   software without specific prior written permission.

# NO EXPRESS OR IMPLIED LICENSES TO ANY PARTY'S PATENT RIGHTS ARE GRANTED BY
# THIS LICENSE. THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND
# CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT
# NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A
# PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR
# CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
# EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
# PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS;
# OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
# WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR
# OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF
# ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

from .basic import (
    Gain,
    Interleave,
    Lambda,
    NamedLayer,
    Reshape,
    Transpose,
)
from .gdn import (
    GDN,
    GDN1,
)
from .layers import (
    AttentionBlock,
    CheckerboardMaskedConv2d,
    MaskedConv2d,
    MultistageMaskedConv2d,
    QReLU,
    ResidualBlock,
    ResidualBlockUpsample,
    ResidualBlockWithStride,
    SpectralConv2d,
    SpectralConvTranspose2d,
    conv,
    conv1x1,
    conv3x3,
    deconv,
    sequential_channel_ramp,
    subpel_conv3x3,
)
from .attn import (
    CausalAttentionModule,
    ConvTransBlock,
    CrossAttention,
    CrossAttentionBlock,
    EntroformerAttention,
    EntroformerAttentionBlock,
    EntroformerBlock,
    EntroformerConfig,
    EntroformerFeedForward,
    EntroformerPreNorm,
    EntroformerUpPixelShuffle,
    NSABlock,
    PatchEmbed1D,
    PatchMerging,
    PatchSplit,
    PatchUnEmbed1D,
    RSTB,
    ResViTBlock,
    SWAtten,
    SwinBlock,
    SwinTransformerBlock,
    TransDecoder,
    TransDecoder2,
    TransHyperScale,
    WMSA,
    WinNoShiftAttention,
    WindowAttention,
    WindowedCrossAttention,
    build_window_attention_mask,
    entroformer_clones,
    infer_swatten_attention_dim,
    infer_swatten_head_dim,
    infer_swatten_window_size,
    pad_to_window_multiple,
    window_partition,
    window_reverse,
)
from .graph import (
    FeatureReshape,
    FeatureRestore,
    GAL,
    GDFN,
    GFA,
    GraphAggregator,
    GraphAttentionLayer,
    GraphDepthwiseFeedForward,
    GraphLayerStack,
    IPGGrapher,
    MGB,
    compute_sobel_gradients,
    cosine_similarity,
    cossim,
    gaussian_blur,
    global_sampling,
    local_sampling,
)
from .ssm import (
    SS2D,
    VSSBlock,
    build_vss_backbone,
    build_vss_context_stage,
    cross_merge,
    cross_scan,
    cross_selective_scan,
    get_selective_scan_backend,
    infer_vss_block_kwargs,
    infer_vss_depths,
    is_mamba_ssm_available,
    is_selective_scan_cuda_available,
    selective_scan,
    selective_scan_ref,
)
from .wave import (
    DWT2D,
    DWT_2D,
    IDWT2D,
    IDWT_2D,
    WLS,
    WaveletResidualBlockUpsample,
    WaveletResidualBlockWithStride,
    WeConveneAnalysisTransform,
    WeConveneHyperAnalysisTransform,
    WeConveneHyperSynthesisTransform,
    WeConveneSynthesisTransform,
    iWLS,
    is_pytorch_wavelets_available,
)
from .lic import (
    ConvolutionalGLU,
    ConvWithDW,
    DepthwiseConv5x5,
    DWConv,
    GatedFFN,
    GatedTransformCNN,
    LayerNorm2d,
    MultiScaleAggregation,
    MutiScaleDictionaryCrossAttentionGLU,
    OLP,
    ResidualBottleneckBlock,
    ResidualBottleneckBlockWithStride,
    ResidualBottleneckBlockWithUpsample,
    ResScaleConvolutionGateBlock,
    Scale,
    SpatialAttentionModule,
    SwinBlockWithConvMulti,
)

__all__ = [
    "AttentionBlock",
    "CausalAttentionModule",
    "CheckerboardMaskedConv2d",
    "ConvolutionalGLU",
    "ConvTransBlock",
    "ConvWithDW",
    "CrossAttention",
    "CrossAttentionBlock",
    "DWConv",
    "DWT2D",
    "DWT_2D",
    "DepthwiseConv5x5",
    "EntroformerAttention",
    "EntroformerAttentionBlock",
    "EntroformerBlock",
    "EntroformerConfig",
    "EntroformerFeedForward",
    "EntroformerPreNorm",
    "EntroformerUpPixelShuffle",
    "FeatureReshape",
    "FeatureRestore",
    "GAL",
    "GDFN",
    "GDN",
    "GDN1",
    "GFA",
    "Gain",
    "GatedFFN",
    "GatedTransformCNN",
    "GraphAggregator",
    "GraphAttentionLayer",
    "GraphDepthwiseFeedForward",
    "GraphLayerStack",
    "IDWT2D",
    "IDWT_2D",
    "IPGGrapher",
    "Interleave",
    "Lambda",
    "LayerNorm2d",
    "MGB",
    "MaskedConv2d",
    "MultiScaleAggregation",
    "MultistageMaskedConv2d",
    "MutiScaleDictionaryCrossAttentionGLU",
    "NSABlock",
    "NamedLayer",
    "OLP",
    "PatchEmbed1D",
    "PatchMerging",
    "PatchSplit",
    "PatchUnEmbed1D",
    "QReLU",
    "RSTB",
    "ResScaleConvolutionGateBlock",
    "ResViTBlock",
    "Reshape",
    "ResidualBlock",
    "ResidualBlockUpsample",
    "ResidualBlockWithStride",
    "ResidualBottleneckBlock",
    "ResidualBottleneckBlockWithStride",
    "ResidualBottleneckBlockWithUpsample",
    "SS2D",
    "SWAtten",
    "Scale",
    "SpatialAttentionModule",
    "SpectralConv2d",
    "SpectralConvTranspose2d",
    "SwinBlock",
    "SwinBlockWithConvMulti",
    "SwinTransformerBlock",
    "TransDecoder",
    "TransDecoder2",
    "TransHyperScale",
    "Transpose",
    "VSSBlock",
    "WLS",
    "WMSA",
    "WaveletResidualBlockUpsample",
    "WaveletResidualBlockWithStride",
    "WeConveneAnalysisTransform",
    "WeConveneHyperAnalysisTransform",
    "WeConveneHyperSynthesisTransform",
    "WeConveneSynthesisTransform",
    "WinNoShiftAttention",
    "WindowAttention",
    "WindowedCrossAttention",
    "build_vss_backbone",
    "build_vss_context_stage",
    "build_window_attention_mask",
    "compute_sobel_gradients",
    "conv",
    "conv1x1",
    "conv3x3",
    "cosine_similarity",
    "cossim",
    "cross_merge",
    "cross_scan",
    "cross_selective_scan",
    "deconv",
    "entroformer_clones",
    "gaussian_blur",
    "get_selective_scan_backend",
    "global_sampling",
    "iWLS",
    "infer_swatten_attention_dim",
    "infer_swatten_head_dim",
    "infer_swatten_window_size",
    "infer_vss_block_kwargs",
    "infer_vss_depths",
    "is_mamba_ssm_available",
    "is_pytorch_wavelets_available",
    "is_selective_scan_cuda_available",
    "local_sampling",
    "pad_to_window_multiple",
    "selective_scan",
    "selective_scan_ref",
    "sequential_channel_ramp",
    "subpel_conv3x3",
    "window_partition",
    "window_reverse",
]

